"""RUN-9 test data — `epic-tasks/37-run9-an-empty-presence-reply-is-not-a-garbled-verdict.md`.

Each scenario = provider script (what the fake provider streams, per candidate
and per call) + [gate1] config overrides + `checks(r)` over the black-box
observables (verdict, request payloads, log lines, counters, sleeps, trace).
See SCENARIOS.md (generated by harness/catalogue.py) for the human-readable
"what goes in / what is expected" list, and RESULTS.md for what each entrant
actually produced.

Metadata read by the generic harness:
  GROUPS         — table columns (label, check-name prefixes)
  BONUS_PREFIXES — checks shown but not counted (beyond the ticket's letter)
  CONFIG_KEYS    — (section, key, default) that agents.ini must document
"""
from __future__ import annotations

import inspect
import json
import re

import provider as P

NUDGE = "IMPORTANT: your previous reply was not valid JSON"

# [gate1] for every scenario unless overridden: the field config's `fast` ladder,
# no learned budget (deterministic max_tokens), no real waiting, one worker.
GATE1_DEFAULTS = {
    "temperature": "0.0", "max_tokens": "4096", "skip_llm": "false",
    "llm_call_retry_wait_sec": "0", "llm_call_retry_max": "1",
    "unparseable_retry_mode": "fast", "unparseable_learn": "false",
    "presence_workers": "1",
}
NEW_COUNTERS = ("presence_empty_transport", "presence_empty_exhausted", "presence_nothink_ignored")


def ck(name, ok, detail=""):
    return {"name": name, "ok": bool(ok), "detail": str(detail)[:300]}


def _counter(r, name):
    v = r.counters.get(name)
    if v is None:
        v = getattr(r.filter, name, None)
    return v


def _same_params(payloads):
    keys = {(p.get("max_tokens"), p.get("temperature")) for p in payloads}
    return len(keys) == 1, sorted(keys, key=str)


def _has_nudge(p):
    return NUDGE in p["messages"][-1]["content"]


def _think_off(p):
    rs = p.get("reasoning")
    return isinstance(rs, dict) and rs.get("exclude") is True


def _classification_lines(r):
    return [m for m in r.log_lines() if "kind=" in m and "empty" in m.lower() and "finish_reason" in m]


_KIND_RE = {k: re.compile(r"empty[\s(=:/\-]*" + k, re.I) for k in ("transport", "exhausted")}


def _says_kind(text, kind):
    return bool(_KIND_RE[kind].search(text or ""))


def _ending_line(r):
    ls = [m for m in r.log_lines(level="WARNING") if "ending unknown" in m]
    return ls[0] if ls else ""


def _unknown_line(r, i=0):
    ls = [m for m in r.log_lines(level="WARNING") if m.startswith(f"Gate1[presence] UNKNOWN 'candidate {i}'")]
    return ls[0] if ls else ""


def _still_unparseable_line(r):
    ls = [m for m in r.log_lines(level="WARNING") if "ending unknown" in m or "still unparseable" in m]
    return ls[0] if ls else ""


# ───────────────────────────── A. transport-empty ─────────────────────────
def _a_transport_then_verdict(r, variant=""):
    c = r.calls(0)
    same, keys = _same_params(c)
    out = [
        ck(f"A{variant}.verdict REJECTED", r.outcome.get("candidate 0") == "rejected", r.outcome),
        ck(f"A{variant}.3 calls", len(c) == 3, f"calls={len(c)}"),
        ck(f"A{variant}.same (max_tokens,temperature)", same and len(c) == 3, keys),
        ck(f"A{variant}.no nudge in 2nd/3rd", len(c) >= 3 and not _has_nudge(c[1]) and not _has_nudge(c[2]),
           [ _has_nudge(p) for p in c]),
        ck(f"A{variant}.retry request byte-identical (messages) to the first", len(c) >= 3 and c[1]["messages"] == c[0]["messages"] and c[2]["messages"] == c[0]["messages"],
           "differs" if len(c) >= 3 and c[1]["messages"] != c[0]["messages"] else "n/a"),
        ck(f"A{variant}.presence_empty_transport==1", _counter(r, "presence_empty_transport") == 1,
           _counter(r, "presence_empty_transport")),
        ck(f"A{variant}.presence_reask==0", _counter(r, "presence_reask") == 0, _counter(r, "presence_reask")),
        ck(f"A{variant}.presence_unknown==0", _counter(r, "presence_unknown") == 0, _counter(r, "presence_unknown")),
    ]
    return out


def a1_checks(r):
    out = _a_transport_then_verdict(r)
    cl = _classification_lines(r)
    out.append(ck("A1.classification line kind=transport", any("kind=transport" in m for m in cl), cl[:2]))
    out.append(ck("A1.classification line carries numbers",
                  any(all(k in m for k in ("finish_reason=", "completion_tokens=", "reasoning_chars=", "elapsed=")) for m in cl),
                  cl[:1]))
    out.append(ck("A1.exactly one classification line per empty reply", len(cl) == 2, len(cl)))
    out.append(ck("A1.split line has new counters", all(f"{k}=" in r.split_line for k in NEW_COUNTERS), r.split_line))
    out.append(ck("A1.counters dict has new keys", all(k in r.counters for k in NEW_COUNTERS), sorted(r.counters)))
    out.append(ck("A1.split shows presence_empty_transport=1", "presence_empty_transport=1" in r.split_line, r.split_line))
    return out


def a4_checks(r):
    c = r.calls(0)
    ul = _unknown_line(r)
    out = [
        ck("A4.ends UNKNOWN, kept", r.outcome.get("candidate 0") == "unknown-kept", r.outcome),
        ck("A4.4 calls (1 + 2 retries + 1 pinned re-ask)", len(c) == 4, f"calls={len(c)} params={[(p.get('max_tokens'), p.get('temperature')) for p in c]}"),
        ck("A4.first 3 calls identical params, no nudge", len(c) >= 3 and _same_params(c[:3])[0] and not any(_has_nudge(p) for p in c[:3]),
           [(p.get("max_tokens"), p.get("temperature"), _has_nudge(p)) for p in c[:3]]),
        ck("A4.UNKNOWN line says 'empty (transport)'", _says_kind(ul, "transport"), ul[:200]),
        ck("A4.'ending unknown' WARNING says 'empty (transport)'", _says_kind(_ending_line(r), "transport"), _ending_line(r)[:200]),
        ck("A4.generic 'JSON decode failed (Expecting value' replaced in UNKNOWN line", ul and "Expecting value" not in ul, ul[:200]),
        ck("A4.presence_empty_transport==1", _counter(r, "presence_empty_transport") == 1, _counter(r, "presence_empty_transport")),
        ck("A4.presence_unknown==1", _counter(r, "presence_unknown") == 1, _counter(r, "presence_unknown")),
        ck("A4.presence_empty_exhausted==0", _counter(r, "presence_empty_exhausted") == 0, _counter(r, "presence_empty_exhausted")),
    ]
    return out


def a5_checks(r):
    ul = _unknown_line(r)
    return [
        ck("A5.ends UNKNOWN, dropped (presence_unknown=reject)", r.outcome.get("candidate 0") == "unknown-dropped", r.outcome),
        ck("A5.UNKNOWN line says 'empty (transport)'", _says_kind(ul, "transport"), ul[:200]),
        ck("A5.4 calls", len(r.calls(0)) == 4, len(r.calls(0))),
    ]


def a6_checks(r):
    c = r.calls(0)
    ul = _unknown_line(r)
    return [
        ck("A6.retries=0: today's 2 calls", len(c) == 2, f"calls={len(c)}"),
        ck("A6.retries=0: 2nd call is the pinned (4096,0.1) re-ask", len(c) >= 2 and (c[1].get("max_tokens"), c[1].get("temperature")) == (4096, 0.1),
           [(p.get("max_tokens"), p.get("temperature")) for p in c]),
        ck("A6.ends UNKNOWN kept", r.outcome.get("candidate 0") == "unknown-kept", r.outcome),
        ck("A6.UNKNOWN or 'ending unknown' line says 'empty (transport)'", _says_kind(ul, "transport") or _says_kind(_ending_line(r), "transport"), ul[:200]),
        ck("A6.classification line present", bool(_classification_lines(r)), _classification_lines(r)[:1]),
    ]


def a7_checks(r):
    c = r.calls(0)
    return [
        ck("A7.retries=0 + verdict on re-ask: REJECTED", r.outcome.get("candidate 0") == "rejected", r.outcome),
        ck("A7.2 calls", len(c) == 2, len(c)),
        ck("A7.presence_reask==1 (today's path)", _counter(r, "presence_reask") == 1, _counter(r, "presence_reask")),
        ck("A7.presence_empty_transport==1 (still classified)", _counter(r, "presence_empty_transport") == 1, _counter(r, "presence_empty_transport")),
    ]


def a8_checks(r):
    c = r.calls(0)
    return [
        ck("A8.presence_empty_retries=1 → 3 calls", len(c) == 3, f"calls={len(c)}"),
        ck("A8.ends UNKNOWN", r.outcome.get("candidate 0", "").startswith("unknown"), r.outcome),
    ]


def a9_checks(r):
    sevens = [x for x in r.sleeps if abs(x - 7.0) < 1e-6]
    return [
        ck("A9.sleeps llm_call_retry_wait_sec (7s) between the 2 transport retries", len(sevens) >= 2, r.sleeps[:10]),
        ck("A9.no sleep before the first call", not r.sleeps or r.sleeps[0] != 7.0 or len(r.calls(0)) >= 2, r.sleeps[:3]),
        ck("A9.ends UNKNOWN", r.outcome.get("candidate 0", "").startswith("unknown"), r.outcome),
    ]


def j2_checks(r):
    c = r.calls(0)
    return [
        ck("J2.429 → transport-empty → verdict: REJECTED", r.outcome.get("candidate 0") == "rejected", r.outcome),
        ck("J2.3 HTTP requests (429 retry + transport retry)", len(c) == 3, len(c)),
        ck("J2.presence_empty_transport==1", _counter(r, "presence_empty_transport") == 1, _counter(r, "presence_empty_transport")),
        ck("J2.presence_unknown==0", _counter(r, "presence_unknown") == 0, _counter(r, "presence_unknown")),
        ck("J2.no nudge anywhere", not any(_has_nudge(p) for p in c), [_has_nudge(p) for p in c]),
    ]


# ───────────────────────────── B. exhausted ────────────────────────────────
def b1_checks(r):
    c = r.calls(0)
    out = [
        ck("B1.exhausted then verdict: REJECTED", r.outcome.get("candidate 0") == "rejected", r.outcome),
        ck("B1.2 calls (no transport retry)", len(c) == 2, f"calls={len(c)} params={[(p.get('max_tokens'), p.get('temperature')) for p in c]}"),
        ck("B1.2nd call pinned at (4096,0.1)", len(c) >= 2 and (c[1].get("max_tokens"), c[1].get("temperature")) == (4096, 0.1),
           [(p.get("max_tokens"), p.get("temperature")) for p in c]),
        ck("B1.presence_reask==1", _counter(r, "presence_reask") == 1, _counter(r, "presence_reask")),
        ck("B1.presence_empty_exhausted==1", _counter(r, "presence_empty_exhausted") == 1, _counter(r, "presence_empty_exhausted")),
        ck("B1.presence_empty_transport==0", _counter(r, "presence_empty_transport") == 0, _counter(r, "presence_empty_transport")),
        ck("B1.classification kind=exhausted", any("kind=exhausted" in m for m in _classification_lines(r)), _classification_lines(r)[:1]),
    ]
    r.info["B1.nudge_on_exhausted_reask"] = len(c) >= 2 and _has_nudge(c[1])
    return out


def b2_checks(r):
    c = r.calls(0)
    ul = _unknown_line(r)
    thinks = [(_think_off(p), (p.get("thinking") or {}).get("type")) for p in c]
    out = [
        ck("B2.exhausted forever (think=false): UNKNOWN kept", r.outcome.get("candidate 0") == "unknown-kept", r.outcome),
        ck("B2.2 calls — no extra no-think call", len(c) == 2, f"calls={len(c)}"),
        ck("B2.UNKNOWN line says 'empty (exhausted)'", _says_kind(ul, "exhausted"), ul[:200]),
        ck("B2.'ending unknown' WARNING says 'empty (exhausted)'", _says_kind(_ending_line(r), "exhausted"), _ending_line(r)[:200]),
        ck("B2.presence_empty_exhausted==1", _counter(r, "presence_empty_exhausted") == 1, _counter(r, "presence_empty_exhausted")),
        ck("B2.every call think=off (unchanged)", all(t[0] for t in thinks), thinks),
    ]
    skip = [m for m in r.log_lines() if "think" in m.lower() and ("nothing to switch" in m.lower() or "already" in m.lower() and "off" in m.lower() or "skip" in m.lower())]
    r.info["B2.nothink_skip_log"] = skip[:2]
    return out


def b3_checks(r):
    c = r.calls(0)
    return [
        ck("B3.finish=stop but completion_tokens=0.95*max → exhausted", any("kind=exhausted" in m for m in _classification_lines(r)), _classification_lines(r)[:1]),
        ck("B3.no transport retry (2 calls)", len(c) == 2, len(c)),
        ck("B3.presence_empty_exhausted==1", _counter(r, "presence_empty_exhausted") == 1, _counter(r, "presence_empty_exhausted")),
    ]


def b4_checks(r):
    c = r.calls(0)
    warn = [m for m in r.log_lines(level="WARNING") if "reasoning_content" in m and "think" in m]
    return [
        ck("B4.reasoning_content + finish=stop → exhausted", any("kind=exhausted" in m for m in _classification_lines(r)), _classification_lines(r)[:1]),
        ck("B4.no transport retry (2 calls)", len(c) == 2, len(c)),
        ck("B4.nothink-ignored WARNING emitted", bool(warn), warn[:1]),
        ck("B4.presence_nothink_ignored>=1", (_counter(r, "presence_nothink_ignored") or 0) >= 1, _counter(r, "presence_nothink_ignored")),
    ]


def b5_checks(r):
    c = r.calls(0)
    cl = _classification_lines(r)
    r.info["B5.kind"] = cl[:1]
    return [
        ck("B5.unclosed <think> + finish=length: not retried as transport", len(c) == 2, f"calls={len(c)}"),
        ck("B5.classified exhausted", any("kind=exhausted" in m for m in cl), cl[:1]),
    ]


# ───────────────────────────── C. no-think rung ────────────────────────────
def c1_checks(r):
    c = r.calls(0)
    last = c[-1] if c else {}
    off_calls = [i for i, p in enumerate(c) if _think_off(p)]
    on_calls = [i for i, p in enumerate(c) if not _think_off(p)]
    log_off = [m for m in r.log_lines() if "think=off" in m or "think=False" in m or "think off" in m.lower()]
    return [
        ck("C1.think=true: a think=off re-ask was made", bool(off_calls), f"off={off_calls} on={on_calls} n={len(c)}"),
        ck("C1.think=off call is the LAST call", bool(c) and _think_off(last), f"last reasoning={last.get('reasoning')} thinking={last.get('thinking')}"),
        ck("C1.exactly one think=off call", len(off_calls) == 1, off_calls),
        ck("C1.think=off payload: no think/reasoning_effort, reasoning.exclude=true",
           bool(c) and "think" not in last and "reasoning_effort" not in last and _think_off(last), sorted(last.keys())),
        ck("C1.think=off payload: thinking.type=disabled (AUTO-ZAITHINK-1 parity)", (last.get("thinking") or {}).get("type") == "disabled", last.get("thinking")),
        ck("C1.think=off at pinned budget + initial temperature", (last.get("max_tokens"), last.get("temperature")) == (4096, 0.0),
           (last.get("max_tokens"), last.get("temperature"))),
        ck("C1.earlier calls went out with think=on", bool(on_calls) and all(not _think_off(c[i]) for i in on_calls), [(p.get("reasoning"), p.get("thinking")) for p in c[:2]]),
        ck("C1.verdict from think=off call used → REJECTED", r.outcome.get("candidate 0") == "rejected", r.outcome),
        ck("C1.logged as think=off re-ask", bool(log_off), log_off[:1]),
        ck("C1.presence_reask==1 (counts as a re-ask)", _counter(r, "presence_reask") == 1, _counter(r, "presence_reask")),
    ]


def c2_checks(r):
    """think=true, exhausted forever incl. the think=off rung → UNKNOWN exhausted, no more than one think=off call."""
    c = r.calls(0)
    off_calls = [i for i, p in enumerate(c) if _think_off(p)]
    return [
        ck("C2.think=true exhausted forever: exactly one think=off call", len(off_calls) == 1, f"off={off_calls} n={len(c)}"),
        ck("C2.3 calls total (initial + pinned re-ask + think=off)", len(c) == 3, [(p.get("max_tokens"), p.get("temperature"), _think_off(p)) for p in c]),
        ck("C2.ends UNKNOWN 'empty (exhausted)'", _says_kind(_unknown_line(r), "exhausted") or _says_kind(_ending_line(r), "exhausted"), _unknown_line(r)[:200]),
    ]


# ───────────────────────────── D. no-think ignored ─────────────────────────
def d1_checks(r):
    warn = [m for m in r.log_lines(level="WARNING") if "reasoning_content" in m and "think" in m]
    cnt = _counter(r, "presence_nothink_ignored")
    r.info["D1.presence_nothink_ignored"] = cnt
    return [
        ck("D1.WARNING emitted exactly once for 5 candidates", len(warn) == 1, f"n={len(warn)} {warn[:1]}"),
        ck("D1.WARNING names url/model", bool(warn) and ("test-model" in warn[0]), warn[:1]),
        ck("D1.presence_nothink_ignored counted (>=1)", (cnt or 0) >= 1, cnt),
        ck("D1.presence_empty_exhausted==5", _counter(r, "presence_empty_exhausted") == 5, _counter(r, "presence_empty_exhausted")),
        ck("D1.presence_empty_transport==0", _counter(r, "presence_empty_transport") == 0, _counter(r, "presence_empty_transport")),
        ck("D1.all 5 UNKNOWN kept", all(v == "unknown-kept" for v in r.outcome.values()), r.outcome),
        ck("D1.2 calls per candidate (no transport retry)", all(len(r.calls(i)) == 2 for i in range(5)), r.info["calls"]),
    ]


def d2_checks(r):
    warn = [m for m in r.log_lines(level="WARNING") if "reasoning_content" in m and "think" in m]
    return [
        ck("D2.workers=4: nothink WARNING still exactly once", len(warn) == 1, f"n={len(warn)}"),
        ck("D2.workers=4: presence_empty_exhausted==8", _counter(r, "presence_empty_exhausted") == 8, _counter(r, "presence_empty_exhausted")),
        ck("D2.workers=4: all UNKNOWN kept", all(v == "unknown-kept" for v in r.outcome.values()), r.outcome),
    ]


# ───────────────────────────── E. stream_options ───────────────────────────
def _so(p):
    return (p.get("stream_options") or {}).get("include_usage")


def e1_checks(r):
    c = r.calls(0)
    return [
        ck("E1.stream_options.include_usage=true in payload", bool(c) and _so(c[0]) is True, c[0].get("stream_options") if c else None),
        ck("E1.stream=true", bool(c) and c[0].get("stream") is True, c[0].get("stream") if c else None),
        ck("E1.verdict REJECTED", r.outcome.get("candidate 0") == "rejected", r.outcome),
    ]


def e2_checks(r):
    c0, c1 = r.calls(0), r.calls(1)
    return [
        ck("E2.first request carried stream_options", bool(c0) and _so(c0[0]) is True, c0[0].get("stream_options") if c0 else None),
        ck("E2.after HTTP 400 the retry omits stream_options", len(c0) >= 2 and all(_so(p) is None for p in c0[1:]), [_so(p) for p in c0]),
        ck("E2.candidate 0 still completes REJECTED", r.outcome.get("candidate 0") == "rejected", r.outcome),
        ck("E2.candidate 1 (same url/model) never sends it again", bool(c1) and all(_so(p) is None for p in c1), [_so(p) for p in c1]),
        ck("E2.candidate 1 REJECTED in one call", len(c1) == 1 and r.outcome.get("candidate 1") == "rejected", len(c1)),
        ck("E2.presence_unknown==0", _counter(r, "presence_unknown") == 0, _counter(r, "presence_unknown")),
    ]


# ───────────────────────────── F. wording / counters ───────────────────────
def f1_checks(r):
    c = r.calls(0)
    ul = _unknown_line(r)
    return [
        ck("F1.garbled forever: UNKNOWN kept", r.outcome.get("candidate 0") == "unknown-kept", r.outcome),
        ck("F1.UNKNOWN or 'ending unknown' line says 'garbled'", "garbled" in ul or "garbled" in _ending_line(r), (ul[:120], _ending_line(r)[:120])),
        ck("F1.no classification line for a non-empty reply", not _classification_lines(r), _classification_lines(r)[:1]),
        ck("F1.presence_empty_* both 0", _counter(r, "presence_empty_transport") == 0 and _counter(r, "presence_empty_exhausted") == 0,
           (_counter(r, "presence_empty_transport"), _counter(r, "presence_empty_exhausted"))),
        ck("F1.nudge sent on garbled re-asks (unchanged)", len(c) >= 2 and all(_has_nudge(p) for p in c[1:]), [_has_nudge(p) for p in c]),
        ck("F1.strict ladder still 7 calls", len(c) == 7, len(c)),
    ]


def f2_checks(r):
    c = r.calls(0)
    return [
        ck("F2.fast garbled: 6 calls (no pin, full grid)", len(c) == 6, [(p.get("max_tokens"), p.get("temperature")) for p in c]),
        ck("F2.ends UNKNOWN kept", r.outcome.get("candidate 0") == "unknown-kept", r.outcome),
        ck("F2.presence_empty_* both 0", _counter(r, "presence_empty_transport") == 0 and _counter(r, "presence_empty_exhausted") == 0,
           (_counter(r, "presence_empty_transport"), _counter(r, "presence_empty_exhausted"))),
    ]


def f4_checks(r):
    n = 12
    return [
        ck("F4.workers=4: presence_empty_transport==12", _counter(r, "presence_empty_transport") == n, _counter(r, "presence_empty_transport")),
        ck("F4.all 12 REJECTED", all(v == "rejected" for v in r.outcome.values()), r.outcome),
        ck("F4.presence_unknown==0", _counter(r, "presence_unknown") == 0, _counter(r, "presence_unknown")),
        ck("F4.3 calls each", all(len(r.calls(i)) == 3 for i in range(n)), r.info["calls"]),
    ]


# ───────────────────────────── G. config ───────────────────────────────────
def g1_checks(r):
    c = r.calls(0)
    warn = [m for m in r.log_lines(level="WARNING") if "presence_empty_retries" in m and "malformed" in m]
    return [
        ck("G1.malformed presence_empty_retries → WARNING", bool(warn), warn[:1]),
        ck("G1.malformed → default 2 (4 calls)", len(c) == 4, len(c)),
        ck("G1.no crash, ends UNKNOWN", r.outcome.get("candidate 0", "").startswith("unknown"), r.outcome),
    ]


# ───────────────────────────── H. cap log ──────────────────────────────────
def h1_checks(r):
    logs = r.log_lines()
    cap_idx = [i for i, m in enumerate(logs) if "capped at unparseable_max_tokens_cap" in m]
    bad = []
    for i in cap_idx:
        cap_m = re.search(r"capped at unparseable_max_tokens_cap=(\d+)", logs[i])
        cap = int(cap_m.group(1)) if cap_m else None
        nxt = logs[i + 1] if i + 1 < len(logs) else ""
        if "already tried" in nxt:
            mt = re.search(r"max_tokens=(\d+)", nxt)
            if mt and int(mt.group(1)) != cap:
                bad.append((logs[i][-80:], nxt[-90:]))
    r.info["H1.cap_lines"] = len(cap_idx)
    return [
        ck("H1.no cap line followed by 'already tried' quoting another max_tokens", not bad, bad[:1]),
        ck("H1.ends UNKNOWN exhausted", _says_kind(_unknown_line(r), "exhausted") or _says_kind(_ending_line(r), "exhausted"), _unknown_line(r)[:160]),
    ]


# ───────────────────────────── I. stream meta (direct) ─────────────────────
_META_ALIASES = {
    "finish_reason": ("finish_reason", "done_reason", "finish"),
    "completion_tokens": ("completion_tokens", "tokens", "eval_count", "usage_completion_tokens", "output_tokens"),
    "reasoning_chars": ("reasoning_chars", "reasoning_content_chars", "reasoning_len", "reasoning_length"),
    "content_chunks": ("content_chunks", "chunks", "content_chunk_count", "n_content_chunks", "content_deltas"),
    "elapsed": ("elapsed", "elapsed_s", "elapsed_sec", "elapsed_seconds", "wall_clock", "wall_s", "duration"),
}


def _meta_get(meta, field):
    for alias in _META_ALIASES[field]:
        if isinstance(meta, dict) and alias in meta:
            return meta[alias], alias
        if hasattr(meta, alias):
            return getattr(meta, alias), alias
    return "<missing>", None


def _meta_api(L):
    """Find the entrant's metadata API. Returns (kind, callable)."""
    if hasattr(L, "request_completion_ex"):
        return "request_completion_ex", L.request_completion_ex
    for name in dir(L):
        if name.startswith("request_completion") and name != "request_completion":
            return name, getattr(L, name)
    sig = inspect.signature(L.request_completion)
    for pname in ("on_meta", "meta_callback", "on_done", "on_finish", "meta"):
        if pname in sig.parameters:
            return f"request_completion({pname}=)", pname
    return None, None


def _call_meta(L, url, headers, payload, api_format="openai"):
    kind, fn = _meta_api(L)
    if kind is None:
        return None, None, "no meta API found"
    if kind.startswith("request_completion("):
        box = {}
        def cb(m, *a, **k):
            box["m"] = m
        res = L.request_completion(url, headers, payload, 10, stream=True, api_format=api_format, **{fn: cb})
        return kind, (res, box.get("m")), None
    res = fn(url, headers, payload, 10, stream=True, api_format=api_format)
    if isinstance(res, tuple) and len(res) == 2:
        return kind, res, None
    # maybe an object with .text/.meta
    text = getattr(res, "text", None)
    if text is not None:
        return kind, (text, res), None
    return kind, (res, None), "unexpected return shape"


def _drive_stream(L, prov, r):
    url = "http://stub.local:1337/v1/chat/completions"
    headers = {"Content-Type": "application/json"}
    base = {"model": "test-model", "messages": [{"role": "user", "content": "Location: x\nhi"}],
            "temperature": 0.0, "max_tokens": 4096}
    out = {}
    specs = {
        "normal": P.rejected(),
        "role_only": P.transport_empty(),
        "role_only_no_finish_no_usage": P.transport_empty(finish_reason=None, usage=None),
        "reasoning_only": P.reasoning_only(),
        "exhausted": P.exhausted_empty(),
        "ollama": {"content": "hello", "finish_reason": "length", "usage": 77, "ollama": True},
        "finish_on_content_then_usage": P.rejected(finish_inline=True, usage=31),
        "usage_inline_on_finish": P.exhausted_empty(usage_inline=True),
    }
    r.info["meta_api"] = _meta_api(L)[0]
    for name, spec in specs.items():
        prov.default = [spec]
        prov.by_key.clear()
        af = "ollama" if spec.get("ollama") else "openai"
        u = "http://stub.local:11434/api/chat" if af == "ollama" else url
        try:
            plain = L.request_completion(u, headers, dict(base), 10, stream=True, api_format=af)
        except Exception as e:  # noqa
            plain = f"<exc {type(e).__name__}: {e}>"
        prov.by_key.clear()
        try:
            kind, res, err = _call_meta(L, u, headers, dict(base), af)
            text, meta = res if res else (None, None)
        except Exception as e:  # noqa
            kind, text, meta, err = None, None, None, f"<exc {type(e).__name__}: {e}>"
        m = {}
        if meta is not None:
            for f in _META_ALIASES:
                m[f] = _meta_get(meta, f)
        out[name] = {"plain": plain, "meta_text": text, "meta": m, "err": err, "meta_repr": repr(meta)[:200]}
    r.info["stream"] = {k: {"plain": v["plain"], "meta": {f: str(x[0])[:40] for f, x in v["meta"].items()}, "err": v["err"]} for k, v in out.items()}
    return out


def i1_checks(r):
    o = r.results
    def mv(name, f):
        return o[name]["meta"].get(f, ("<missing>", None))[0]
    def num(x):
        try:
            return float(x)
        except Exception:
            return None
    checks = [
        ck("I1.plain request_completion: normal text unchanged", o["normal"]["plain"] == P.rejected()["content"], o["normal"]["plain"]),
        ck("I1.plain: role-only+[DONE] → ''", o["role_only"]["plain"] == "", repr(o["role_only"]["plain"])),
        ck("I1.plain: reasoning-only → ''", o["reasoning_only"]["plain"] == "", repr(o["reasoning_only"]["plain"])),
        ck("I1.plain: ollama text unchanged", o["ollama"]["plain"] == "hello", repr(o["ollama"]["plain"])),
        ck("I2.meta API exists", r.info.get("meta_api") is not None, r.info.get("meta_api")),
        ck("I2.meta: role-only → text ''", o["role_only"]["meta_text"] == "", repr(o["role_only"]["meta_text"])),
        ck("I2.meta: role-only content_chunks==0", num(mv("role_only", "content_chunks")) == 0, mv("role_only", "content_chunks")),
        ck("I2.meta: role-only finish_reason=='stop'", mv("role_only", "finish_reason") == "stop", mv("role_only", "finish_reason")),
        ck("I2.meta: role-only completion_tokens==0 (usage chunk)", num(mv("role_only", "completion_tokens")) == 0, mv("role_only", "completion_tokens")),
        ck("I2.meta: no usage chunk → completion_tokens is None", mv("role_only_no_finish_no_usage", "completion_tokens") is None, mv("role_only_no_finish_no_usage", "completion_tokens")),
        ck("I2.meta: no finish chunk → finish_reason is None", mv("role_only_no_finish_no_usage", "finish_reason") is None, mv("role_only_no_finish_no_usage", "finish_reason")),
        ck("I2.meta: reasoning-only → text '' and reasoning_chars>0", o["reasoning_only"]["meta_text"] == "" and (num(mv("reasoning_only", "reasoning_chars")) or 0) > 0, mv("reasoning_only", "reasoning_chars")),
        ck("I2.meta: reasoning-only finish_reason=='length'", mv("reasoning_only", "finish_reason") == "length", mv("reasoning_only", "finish_reason")),
        ck("I2.meta: exhausted completion_tokens==4096", num(mv("exhausted", "completion_tokens")) == 4096, mv("exhausted", "completion_tokens")),
        ck("I2.meta: normal content_chunks>0", (num(mv("normal", "content_chunks")) or 0) > 0, mv("normal", "content_chunks")),
        ck("I2.meta: elapsed is a number", num(mv("normal", "elapsed")) is not None, mv("normal", "elapsed")),
        ck("I4.meta: finish_reason on content chunk survives a trailing usage chunk (last non-null)", mv("finish_on_content_then_usage", "finish_reason") == "stop", mv("finish_on_content_then_usage", "finish_reason")),
        ck("I4.meta: completion_tokens from trailing usage chunk", num(mv("finish_on_content_then_usage", "completion_tokens")) == 31, mv("finish_on_content_then_usage", "completion_tokens")),
        ck("I4.meta: usage inline on the finish chunk is read", num(mv("usage_inline_on_finish", "completion_tokens")) == 4096, mv("usage_inline_on_finish", "completion_tokens")),
        ck("I3.meta: ollama done_reason→finish_reason", mv("ollama", "finish_reason") == "length", mv("ollama", "finish_reason")),
        ck("I3.meta: ollama eval_count→completion_tokens", num(mv("ollama", "completion_tokens")) == 77, mv("ollama", "completion_tokens")),
    ]
    return checks


# ───────────────────────────── scenario table ──────────────────────────────
def _plan1(*specs):
    return lambda n: {f"tools/c{i}.py": list(specs) for i in range(n)}


SCENARIOS = {
    # A — transport
    "A1_transport_then_verdict": {"plans": _plan1(P.transport_empty(), P.transport_empty(), P.rejected()), "checks": a1_checks},
    "A2_transport_role_content_empty": {"plans": _plan1(P.transport_empty(role_content=""), P.transport_empty(role_content=""), P.rejected()),
                                        "checks": lambda r: _a_transport_then_verdict(r, "2")},
    "A3_transport_bare_no_usage_no_finish": {"plans": _plan1(P.transport_empty(finish_reason=None, usage=None), P.transport_empty(finish_reason=None, usage=None), P.rejected()),
                                             "checks": lambda r: _a_transport_then_verdict(r, "3")},
    "A4_transport_forever_keep": {"plans": _plan1(P.transport_empty()), "checks": a4_checks},
    "A5_transport_forever_reject": {"plans": _plan1(P.transport_empty()), "config": {"presence_unknown": "reject"}, "checks": a5_checks},
    "A6_retries0_transport_forever": {"plans": _plan1(P.transport_empty()), "config": {"presence_empty_retries": "0"}, "checks": a6_checks},
    "A7_retries0_transport_then_verdict": {"plans": _plan1(P.transport_empty(), P.rejected()), "config": {"presence_empty_retries": "0"}, "checks": a7_checks},
    "A8_retries1_transport_forever": {"plans": _plan1(P.transport_empty()), "config": {"presence_empty_retries": "1"}, "checks": a8_checks},
    "A9_transport_retry_sleeps": {"plans": _plan1(P.transport_empty()), "config": {"llm_call_retry_wait_sec": "7"}, "checks": a9_checks},
    "J2_429_then_transport_then_verdict": {"plans": _plan1({"http": (429, "Server is busy, retry in 1s")}, P.transport_empty(), P.rejected()), "checks": j2_checks},
    # B — exhausted
    "B1_exhausted_then_verdict": {"plans": _plan1(P.exhausted_empty(), P.rejected()), "checks": b1_checks},
    "B2_exhausted_forever_think_false": {"plans": _plan1(P.exhausted_empty()), "checks": b2_checks},
    "B3_exhausted_by_usage_ratio": {"plans": _plan1(P.transport_empty(usage=lambda p: int(p["max_tokens"] * 0.95)), P.rejected()), "checks": b3_checks},
    "B4_exhausted_by_reasoning_finish_stop": {"plans": _plan1(P.reasoning_only(finish_reason="stop", usage=12), P.rejected()), "checks": b4_checks},
    "B5_unclosed_think_length": {"plans": _plan1({"content": "<think>hmm hmm hmm", "finish_reason": "length", "usage": lambda p: int(p["max_tokens"])}, P.rejected()), "checks": b5_checks},
    # C — no-think rung
    "C1_nothink_rung_verdict": {"plans": _plan1(lambda p: P.rejected() if _think_off(p) else P.exhausted_empty()),
                                "config": {"think": "true"}, "checks": c1_checks},
    "C2_nothink_rung_exhausted_forever": {"plans": _plan1(P.exhausted_empty()), "config": {"think": "true"}, "checks": c2_checks},
    # D — nothink ignored
    "D1_nothink_ignored_5": {"plans": _plan1(P.reasoning_only()), "candidates": 5, "checks": d1_checks},
    "D2_nothink_ignored_workers4": {"plans": _plan1(P.reasoning_only()), "candidates": 8, "config": {"presence_workers": "4"}, "checks": d2_checks},
    # E — stream_options
    "E1_stream_options_present": {"plans": _plan1(P.rejected()), "checks": e1_checks},
    "E2_stream_options_400_memory": {"plans": lambda n: {"tools/c0.py": [{"http": (400, '{"error": {"message": "Unrecognized request argument supplied: stream_options", "type": "invalid_request_error"}}')}, P.rejected()],
                                                         "tools/c1.py": [P.rejected()]},
                                     "candidates": 2, "checks": e2_checks},
    # F — wording/counters/concurrency
    "F1_garbled_forever_strict": {"plans": _plan1(P.garbled()), "config": {"unparseable_retry_mode": "strict"}, "checks": f1_checks},
    "F2_garbled_forever_fast": {"plans": _plan1(P.garbled()), "checks": f2_checks},
    "F4_concurrency_counters": {"plans": _plan1(P.transport_empty(), P.transport_empty(), P.rejected()), "candidates": 12,
                                "config": {"presence_workers": "4"}, "checks": f4_checks},
    # G — config
    "G1_malformed_retries": {"plans": _plan1(P.transport_empty()), "config": {"presence_empty_retries": "abc"}, "checks": g1_checks},
    # H — cap log
    "H1_cap_log": {"plans": _plan1(P.exhausted_empty()), "config": {"unparseable_max_tokens_cap": "8192"}, "checks": h1_checks},
    # I — stream meta
    "I1_stream_meta": {"mode": "stream", "default": [P.rejected()], "drive": _drive_stream, "checks": i1_checks},
}


# ───────────────────────────── K. discriminators (round 2) ─────────────────
def k1_checks(r):
    c = r.calls(0)
    same, keys = _same_params(c)
    return [
        ck("K1.ollama transport-empty ×2 then verdict: REJECTED", r.outcome.get("candidate 0") == "rejected", r.outcome),
        ck("K1.ollama 3 calls, same params", len(c) == 3 and same, f"calls={len(c)} {keys}"),
        ck("K1.ollama presence_empty_transport==1", _counter(r, "presence_empty_transport") == 1, _counter(r, "presence_empty_transport")),
        ck("K1.ollama payload carries no stream_options", all("stream_options" not in p for p in c), [sorted(p.keys()) for p in c[:1]]),
        ck("K1.ollama classification line kind=transport", any("kind=transport" in m for m in _classification_lines(r)), _classification_lines(r)[:1]),
    ]


def k1b_checks(r):
    c = r.calls(0)
    return [
        ck("K1b.ollama done_reason=length/eval_count=max → exhausted (2 calls)", len(c) == 2 and any("kind=exhausted" in m for m in _classification_lines(r)),
           f"calls={len(c)} {_classification_lines(r)[:1]}"),
        ck("K1b.ollama presence_empty_exhausted==1", _counter(r, "presence_empty_exhausted") == 1, _counter(r, "presence_empty_exhausted")),
        ck("K1b.ollama REJECTED via pinned re-ask", r.outcome.get("candidate 0") == "rejected", r.outcome),
    ]


def k2_checks(r):
    c = r.calls(0)
    return [
        ck("K2.usage inline on finish chunk: completion_tokens read → exhausted", any("kind=exhausted" in m for m in _classification_lines(r)), _classification_lines(r)[:1]),
        ck("K2.2 calls (no transport retry)", len(c) == 2, len(c)),
        ck("K2.classification line shows completion_tokens=4096", any("completion_tokens=4096" in m for m in _classification_lines(r)), _classification_lines(r)[:1]),
    ]


def k5_checks(r):
    c = r.calls(0)
    ul = _unknown_line(r)
    return [
        ck("K5.transport then garbled forever: 7 calls (retry + full fast grid, no pin)", len(c) == 7, [(p.get("max_tokens"), p.get("temperature")) for p in c]),
        ck("K5.presence_empty_transport==1", _counter(r, "presence_empty_transport") == 1, _counter(r, "presence_empty_transport")),
        ck("K5.ends UNKNOWN 'garbled'", "garbled" in ul or "garbled" in _ending_line(r), (ul[:100], _ending_line(r)[:100])),
        ck("K5.nudge on the ladder re-asks (garbled path unchanged)", len(c) >= 3 and all(_has_nudge(p) for p in c[2:]), [_has_nudge(p) for p in c]),
        ck("K5.no nudge on the transport retry", len(c) >= 2 and not _has_nudge(c[1]), _has_nudge(c[1]) if len(c) >= 2 else None),
    ]


def k6_checks(r):
    c = r.calls(0)
    r.info["K6.calls"] = [(p.get("max_tokens"), p.get("temperature"), _has_nudge(p)) for p in c]
    r.info["K6.kinds"] = [m.split("kind=")[1][:12] for m in _classification_lines(r)]
    return [
        ck("K6.transport → exhausted → verdict: REJECTED", r.outcome.get("candidate 0") == "rejected", r.outcome),
        ck("K6.presence_unknown==0", _counter(r, "presence_unknown") == 0, _counter(r, "presence_unknown")),
    ]


def k7_checks(r):
    cl = _classification_lines(r)
    vals = [float(m.split("elapsed=")[1].split("s")[0]) for m in cl if "elapsed=" in m]
    return [
        ck("K7.elapsed in classification line is measured (>=0.1s for a 0.15s stream)", bool(vals) and vals[0] >= 0.1, vals),
    ]


def e3_checks(r):
    c0, c1 = r.calls(0), r.calls(1)
    return [
        ck("E3.OpenAI wording 'Unknown parameter: stream_options' → stripped", len(c0) >= 2 and _so(c0[0]) is True and all(_so(p) is None for p in c0[1:]), [_so(p) for p in c0]),
        ck("E3.candidate 0 REJECTED", r.outcome.get("candidate 0") == "rejected", r.outcome),
        ck("E3.candidate 1 never sends it", bool(c0) and _so(c0[0]) is True and bool(c1) and all(_so(p) is None for p in c1), [_so(p) for p in c1]),
    ]


def e4_checks(r):
    c0, c1 = r.calls(0), r.calls(1)
    return [
        ck("E4.unrelated 400: stream_options NOT stripped for later calls", bool(c1) and all(_so(p) is True for p in c1), [_so(p) for p in c1]),
        ck("E4.unrelated 400: candidate 0 ends UNKNOWN (LLM call failed)", r.outcome.get("candidate 0", "").startswith("unknown"), r.outcome),
        ck("E4.unrelated 400: retry still carried stream_options", all(_so(p) is True for p in c0), [_so(p) for p in c0]),
        ck("E4.candidate 1 REJECTED", r.outcome.get("candidate 1") == "rejected", r.outcome),
    ]


def h2_checks(r):
    logs = [m for (lv, n, m) in r.logs if n.startswith("tools.auto.gate1")]
    cap_idx = [i for i, m in enumerate(logs) if "capped at unparseable_max_tokens_cap" in m]
    bad = []
    for i in cap_idx:
        nxt = logs[i + 1] if i + 1 < len(logs) else ""
        mt = re.search(r"max_tokens=(\d+)", nxt)
        if not ("re-asking" in nxt and mt and int(mt.group(1)) == 8192):
            bad.append(nxt[-120:])
    c = r.calls(0)
    return [
        ck("H2.strict+cap: cap line exists (legit cap use)", bool(cap_idx), len(cap_idx)),
        ck("H2.strict+cap: every cap line is followed by a re-ask at max_tokens=8192", bool(cap_idx) and not bad, bad[:1]),
        ck("H2.strict+cap: no request above 8192", all((p.get("max_tokens") or 0) <= 8192 for p in c), sorted({p.get("max_tokens") for p in c}, key=str)),
    ]


def c3a_checks(r):
    c = r.calls(0)
    off = [i for i, p in enumerate(c) if _think_off(p)]
    return [
        ck("C3a.profile think=true (gate1 think=false): think=off rung fires", len(off) == 1 and _think_off(c[-1]), f"off={off} n={len(c)}"),
        ck("C3a.calls go to the profile model", bool(c) and all(p.get("model") == "profile-model" for p in c), c[0].get("model") if c else None),
        ck("C3a.REJECTED from the think=off call", r.outcome.get("candidate 0") == "rejected", r.outcome),
    ]


def c3b_checks(r):
    c = r.calls(0)
    return [
        ck("C3b.profile think=false (gate1 think=true): no think=off rung, 2 calls", len(c) == 2 and all(_think_off(p) for p in c), f"n={len(c)} {[(_think_off(p)) for p in c]}"),
        ck("C3b.ends UNKNOWN exhausted", _says_kind(_unknown_line(r), "exhausted") or _says_kind(_ending_line(r), "exhausted"), _unknown_line(r)[:120]),
    ]


def k4_checks(r):
    cl = _classification_lines(r)
    r.info["K4.kind"] = cl[:1]
    return [
        ck("K4.bonus: OpenRouter `reasoning` delta key counted as reasoning (→ exhausted)", any("kind=exhausted" in m for m in cl), cl[:1]),
    ]


_PROFILE = {"gate1_llm": {"base_url": "http://stub.local:1337/v1", "api_key": "test", "model": "profile-model", "api_format": "openai"}}

SCENARIOS.update({
    "K1_ollama_transport_then_verdict": {"api_format": "ollama", "plans": _plan1(P.transport_empty(ollama=True, usage=0), P.transport_empty(ollama=True, usage=0), P.rejected(ollama=True)), "checks": k1_checks},
    "K1b_ollama_exhausted_then_verdict": {"api_format": "ollama", "plans": _plan1(P.exhausted_empty(ollama=True), P.rejected(ollama=True)), "checks": k1b_checks},
    "K2_usage_inline_on_finish_chunk": {"plans": _plan1(P.exhausted_empty(finish_reason="stop", usage_inline=True), P.rejected()), "checks": k2_checks},
    "K4_bonus_reasoning_key_openrouter": {"plans": _plan1(P.reasoning_only(reasoning_key="reasoning", finish_reason="stop", usage=12), P.rejected()), "checks": k4_checks},
    "K5_transport_then_garbled_forever": {"plans": _plan1(P.transport_empty(), P.garbled()), "checks": k5_checks},
    "K6_transport_then_exhausted_then_verdict": {"plans": _plan1(P.transport_empty(), P.exhausted_empty(), P.rejected()), "checks": k6_checks},
    "K7_elapsed_measured": {"plans": _plan1(P.transport_empty(delay=0.15), P.rejected()), "checks": k7_checks},
    "E3_stream_options_400_openai_wording": {"plans": lambda n: {"tools/c0.py": [{"http": (400, '{"error": {"message": "Unknown parameter: \'stream_options\'.", "type": "invalid_request_error", "param": "stream_options", "code": "unknown_parameter"}}')}, P.rejected()],
                                                                 "tools/c1.py": [P.rejected()]}, "candidates": 2, "checks": e3_checks},
    "E4_unrelated_400_keeps_stream_options": {"plans": lambda n: {"tools/c0.py": [{"http": (400, '{"error": {"message": "The model `test-model` does not exist", "type": "invalid_request_error"}}')}],
                                                                  "tools/c1.py": [P.rejected()]}, "candidates": 2, "checks": e4_checks},
    "H2_cap_legit_strict": {"plans": _plan1(P.garbled()), "config": {"unparseable_retry_mode": "strict", "unparseable_max_tokens_cap": "8192"}, "checks": h2_checks},
    "C3a_profile_think_true": {"plans": _plan1(lambda p: P.rejected() if _think_off(p) else P.exhausted_empty()),
                               "config": {"think": "false", "presence_llm_profile": "gate1_llm"},
                               "extra_sections": {"gate1_llm": dict(_PROFILE["gate1_llm"], think="true")}, "checks": c3a_checks},
    "C3b_profile_think_false": {"plans": _plan1(P.exhausted_empty()),
                                "config": {"think": "true", "presence_llm_profile": "gate1_llm"},
                                "extra_sections": {"gate1_llm": dict(_PROFILE["gate1_llm"], think="false")}, "checks": c3b_checks},
})


# ───────────────────────────── L. round 3 ──────────────────────────────────
def l1_checks(r):
    c0, c1 = r.calls(0), r.calls(1)
    mts = [p.get("max_tokens") for p in c1]
    return [
        ck("L1.learned budget (8192) reused by every transport retry", len(c1) == 3 and mts == [8192, 8192, 8192], mts),
        ck("L1.candidate 1 REJECTED", r.outcome.get("candidate 1") == "rejected", r.outcome),
        ck("L1.candidate 0 learned at 8192 (precondition)", bool(c0) and c0[-1].get("max_tokens") == 8192, [p.get("max_tokens") for p in c0]),
    ]


def l2_checks(r):
    ul = _unknown_line(r)
    reqs = [e for e in r.tracer.events if e["kind"] == "llm_request"]
    resps = [e for e in r.tracer.events if e["kind"] == "llm_response"]
    return [
        ck("L2.UNKNOWN reason counts ladder re-asks only ('after 1 re-ask(s)')", "after 1 re-ask(s)" in ul, ul[:160]),
        ck("L3.trace: one llm_request event per HTTP call (4)", len(reqs) == 4, len(reqs)),
        ck("L3.trace: one llm_response event per HTTP call (4)", len(resps) == 4, len(resps)),
        ck("L3.trace: llm_request params carry the candidate title", all(e["params"].get("candidate") == "candidate 0" for e in reqs), reqs[:1]),
    ]


def l4_checks(r):
    cl = _classification_lines(r)
    vals = [float(m.split("elapsed=")[1].split("s")[0]) for m in cl if "elapsed=" in m]
    return [
        ck("L4.elapsed is per call, not cumulative (every logged value 0.1–0.3s)", bool(vals) and all(0.1 <= v <= 0.3 for v in vals), vals),
    ]


def k8_checks(r):
    c = r.calls(0)
    r.info["K8.outcome"] = r.outcome
    r.info["K8.calls"] = len(c)
    o = r.outcome.get("candidate 0")
    return [
        ck("K8.404 during a transport retry: filter() does not raise", o is not None, r.outcome),
        ck("K8.404 is never turned into a REJECTED verdict (RUN-5 shape kept)", o == "unknown-kept" or (o == "rejected" and len(c) == 3), f"{o} calls={len(c)}"),
        ck("K8.soft: outer llm_call_retry gives the candidate one more chance → REJECTED", o == "rejected" and len(c) == 3, f"{o} calls={len(c)}"),
    ]


def _drive_stream_options(L, prov, r):
    import inspect as _i
    url = "http://stub.local:1337/v1/chat/completions"
    headers = {"Content-Type": "application/json"}
    out = {}
    sig = _i.signature(L.build_chat_request)
    r.info["build_chat_request_has_stream_param"] = "stream" in sig.parameters
    for stream in (False, True):
        kw = {"stream": stream} if "stream" in sig.parameters else {}
        u, h, payload = L.build_chat_request(base_url="http://stub.local:1337/v1", api_key="k", model="test-model", api_format="openai",
                                             temperature=0.0, max_tokens=64, system="s", user_msg="Location: x\nhi", think=False, **kw)
        prov.default = [P.rejected()]
        prov.requests.clear()
        tokens = []
        text = L.request_completion(u, h, payload, 10, stream=stream, api_format="openai", on_token=tokens.append)
        sent = prov.requests[-1]["payload"]
        out[stream] = {"text": text, "tokens": tokens, "sent_so": sent.get("stream_options"), "sent_stream": sent.get("stream")}
    return out


def i5_checks(r):
    o = r.results
    return [
        ck("I5.stream=False request carries NO stream_options (OpenAI 400s otherwise)", o[False]["sent_so"] is None, o[False]["sent_so"]),
        ck("I5.stream=True request carries stream_options.include_usage", (o[True]["sent_so"] or {}).get("include_usage") is True, o[True]["sent_so"]),
        ck("I6.on_token still receives every content piece", "".join(o[True]["tokens"]) == o[True]["text"] and len(o[True]["tokens"]) >= 2, (len(o[True]["tokens"]), o[True]["text"][:40])),
        ck("I6.non-stream text unchanged", o[False]["text"] == P.rejected()["content"], o[False]["text"]),
    ]


SCENARIOS.update({
    "L1_learned_budget_reused_by_transport_retry": {
        "plans": lambda n: {"tools/c0.py": [P.garbled(), P.garbled(), P.garbled(), P.rejected()],
                            "tools/c1.py": [P.transport_empty(), P.transport_empty(), P.rejected()]},
        "candidates": 2, "config": {"unparseable_learn": "true", "presence_workers": "1"}, "checks": l1_checks},
    "L2_L3_reask_count_and_trace": {"plans": _plan1(P.transport_empty()), "checks": l2_checks},
    "L4_elapsed_per_call": {"plans": _plan1(P.transport_empty(delay=0.15), P.transport_empty(delay=0.15), P.rejected()), "checks": l4_checks},
    "K8_404_during_transport_retry": {"plans": _plan1(P.transport_empty(), {"http": (404, "not found")}, P.rejected()), "checks": k8_checks},
    "I5_stream_options_only_when_streaming": {"mode": "stream", "default": [P.rejected()], "drive": _drive_stream_options, "checks": i5_checks},
})


# ───────────────────────────── metadata for the generic harness ────────────
GROUPS = [
    ("A transport", ("A",)),
    ("B exhausted", ("B",)),
    ("C nothink-rung", ("C1", "C2")),
    ("D nothink-ign", ("D",)),
    ("E stream_opts", ("E1", "E2")),
    ("F wording/ctr", ("F",)),
    ("G/H cfg+cap", ("G", "H1")),
    ("I meta API", ("I1", "I2", "I3")),
    ("J mine", ("J",)),
    ("K/L r2-3", ("K1", "K2", "K5", "K6", "K7", "K8", "L", "E3", "E4", "H2", "C3", "I4", "I5", "I6")),
    ("K4 bonus", ("K4",)),
    ("S static", ("S.",)),
]
BONUS_PREFIXES = ("K4",)
CONFIG_KEYS = [("gate1", "presence_empty_retries", 2)]
