"""catalogue.py <scenarios.py> <results.json> [--base base] — write the scenario catalogue (markdown).

For every scenario: what the fake provider streams per candidate and per call,
the [gate1] overrides, and the checks (= what is expected). The `base` column
says whether the unpatched tree already passes a check (a regression guard)
or fails it (the check measures the fix).
"""
import argparse
import importlib.util
import json
import sys
from pathlib import Path


def spec_str(spec) -> str:
    if callable(spec):
        return "callable(payload) → spec (see scenarios.py)"
    if "http" in spec:
        return f"HTTP {spec['http'][0]} body={spec['http'][1][:70]!r}"
    if "exc" in spec:
        return f"raise {spec['exc']}"
    parts = [spec.get("_name", "sse")]
    for k in ("finish_reason", "usage", "reasoning_key", "role_content", "delay", "ollama", "finish_inline", "usage_inline", "role_chunk"):
        if k in spec:
            v = spec[k]
            if callable(v):
                v = "f(max_tokens)"
            parts.append(f"{k}={v!r}")
    c = spec.get("content")
    if c is None:
        parts.append("content=∅")
    elif callable(c):
        parts.append("content=confirmed(evidence from code block)")
    else:
        parts.append(f"content={c[:50]!r}")
    if spec.get("reasoning"):
        parts.append(f"reasoning={len(spec['reasoning'])} chars")
    return " ".join(parts)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("scenarios")
    ap.add_argument("results")
    ap.add_argument("--base", default="base")
    a = ap.parse_args()
    spec = importlib.util.spec_from_file_location("scenarios", a.scenarios)
    mod = importlib.util.module_from_spec(spec)
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    spec.loader.exec_module(mod)
    R = json.load(open(a.results))
    base = R.get(a.base, {})
    names_by_sc = {}
    for scs in R.values():
        for scn, sc in scs.items():
            if len(sc["checks"]) > len(names_by_sc.get(scn, [])):
                names_by_sc[scn] = sc["checks"]
    print(f"# Scenario catalogue — {Path(a.scenarios).parent.name}\n")
    print(f"Generated by `harness/catalogue.py` from `{Path(a.scenarios).name}` and `{Path(a.results).name}`. "
          f"{len(mod.SCENARIOS)} scenarios, {sum(len(v) for v in names_by_sc.values())} checks. "
          f"`base` = the unpatched tree: ✗ means the check measures the fix, ✓ means it is a regression guard.\n")
    if hasattr(mod, "GATE1_DEFAULTS"):
        print("Default `[gate1]` config for every scenario: `" + "`, `".join(f"{k}={v}" for k, v in mod.GATE1_DEFAULTS.items()) + "`\n")
    print("Static ground-rule checks (`S0_static`, harness/static_checks.py):\n")
    for c in names_by_sc.get("S0_static", []):
        b = base.get("S0_static", {}).get("checks", [])
        bok = next((x["ok"] for x in b if x["name"] == c["name"]), None)
        print(f"- `{c['name']}` — base: {'✓' if bok else '✗'}")
    print()
    for name, sc in mod.SCENARIOS.items():
        print(f"## {name}\n")
        meta = []
        if sc.get("mode"):
            meta.append(f"mode=`{sc['mode']}`")
        if sc.get("api_format"):
            meta.append(f"api_format=`{sc['api_format']}`")
        meta.append(f"candidates={sc.get('candidates', 1)}")
        if sc.get("config"):
            meta.append("[gate1] overrides: " + ", ".join(f"`{k}={v}`" for k, v in sc["config"].items()))
        if sc.get("extra_sections"):
            meta.append("extra sections: " + json.dumps(sc["extra_sections"]))
        print("- " + "; ".join(meta))
        if sc.get("mode") == "stream":
            print(f"- driver: `{sc['drive'].__name__}` (direct `tools.llm_stream` calls; see scenarios.py)")
        else:
            n = sc.get("candidates", 1)
            plans = sc["plans"](n) if callable(sc["plans"]) else sc["plans"]
            seen = {}
            for key, plan in plans.items():
                sig = tuple(spec_str(s) for s in plan)
                seen.setdefault(sig, []).append(key)
            for sig, keys in seen.items():
                who = keys[0] if len(keys) == 1 else f"{keys[0]} … {keys[-1]} ({len(keys)})"
                print(f"- provider script for `{who}` (last reply repeats):")
                for i, s in enumerate(sig, 1):
                    print(f"    {i}. {s}")
        print("- expected:")
        b = base.get(name, {}).get("checks", [])
        for c in names_by_sc.get(name, []):
            bok = next((x["ok"] for x in b if x["name"] == c["name"]), None)
            print(f"    - {'✓' if bok else '✗'} `{c['name']}`")
        print()


if __name__ == "__main__":
    main()
